

pages = [
    """

    The key to a good life is giving a fuck about less, giving a fuck about only what is true and immediate and important.\n,
Wanting positive experience is a negative experience; accepting negative experience is a positive experience.\n,
The more you desperately want to be sexy and desired, the uglier you come to see yourself, regardless of your actual physical appearance.\n,
The more you desperately want to be happy and loved, the lonelier and more afraid you become, regardless of those who surround you.\n,
The more you want to be spiritually enlightened, the more self-centered and shallow you become in trying to get there.\n,
Everything worthwhile in life is won through surmounting the associated negative experience. Any attempt to escape it only backfires.\n,
Learn how to focus and prioritize your thoughts effectively - how to pick and choose what matters to you and what does not matter to you based on finely honed personal values.\n,
Say "fuck it" to everything unimportant in life.\n,
The point isn"t to get away from the shit. The point is to find the shit you enjoy dealing with.\n,
What most pampered people consider "life problems" are really just side effects of not having anything more important to worry about.\n,
Suffering is nature's preferred agent for inspiring change.\n,
The emotional pain of rejection or failure teaches us how to avoid making the same mistakes in the future.\n,
The solution to one problem is merely the creation of the next.\n,
Happiness comes from solving problems.\n,
To be happy we need something to solve.\n,
Solving problems is hard and often feels bad.\n,
Blame and denial give us a quick high: a way to temporarily escape our problems.\n,
Nobody who is actually happy has to stand in front of a mirror and tell himself that he's happy.\n
""","""
If you feel crappy it's because your brain is telling you that there's a problem that's unaddressed or unresolved.\n,
Negative emotions are a call to action.\n,
Positive emotions, on the other hand, are rewards for taking the proper action.\n,
Just because something feels good doesn't mean it is good. Just because something feels bad doesn't mean it is bad. Emotions are merely signposts or suggestions. Make a habit of questioning them.\n,
People overidentify with their emotions. "I was really mad; I couldn't help it."\n,
Emotional intuition, without the aid of reason to keep it in line, sucks.\n,
Happiness requires struggle. It grows from problems.\n,
I was in love with the result, but I wasn't in love with the process. And because of that, I failed at it. The common cultural narratives would tell me that I gave up on my dream. The truth is, I thought I wanted something, but it turns out I didn't. End of story.\n,
There's no such thing as a personal problem. If you've got a problem, chances are millions of other people have had it in the past.\n,
The easier and more problem-free our lives become, the more we seem to feel entitled for them to get even better.\n,
Entitlement is linked to mass-media-driven exceptionalism.\n,
Exceptional information drives us to feel insecure, so we feel the need to compensate through entitlement and addiction, feel the need to be more extreme, more radical, and more self-assured to get noticed or even matter.\n,
Technology has solved old economic problems by giving us new psychological problems.\n,
If the worst thing you can be is in the middle of the bell curve, it then becomes better to be at the extreme low end, because at least there you're still special and deserve attention: the most miserable, or the most oppressed, or the most victimized.\n,
The rare people who do become truly exceptional at something do so because they're obsessed with improvement, which stems from an unerring belief that they are, in fact, not that great at all. It's anti-entitlement.\n,
The vast majority of your life will be boring and not noteworthy, and that's okay.\n,
Acceptance of your own mundane existence will free you to accomplish what you truly wish to accomplish, without judgment or lofty expectations.\n
""","""
Self-awareness is like an onion. There are multiple layers to it:\n,
The first layer is a simple understanding of one's emotions.\n,
We all have blind spots.\n,
The second layer is an ability to ask why we feel certain emotions.\n,
Why do you feel angry? Is it because you failed to achieve some goal?\n,
Why do you feel lethargic and uninspired? Is it because you don't think you're good enough?\n,
Understand the root cause of the emotions that overwhelm you.\n,
The third layer is our personal values.\n,
Why do I consider this to be success/failure?\n,
How am I choosing to measure myself?\n,
By what standard am I judging myself and everyone around me?\n,
If what we value is poorly chosen, then everything will be out of whack.\n,
Everything we think and feel about a situation ultimately comes back to how valuable we perceive it to be.\n,
In the long run, completing a marathon makes us happier than eating a chocolate cake.\n,
In retrospect, the years of struggle will strike you as the most beautiful.\n,
Good values are\n,
1) reality-based\n,
2) socially constructive\n,
3) immediate and controllable.\n,
Bad values are\n,
1) superstitious\n,
2) socially destructive\n,
3) not immediate or controllable.\n,
The difference between a problem being painful or being powerful is a sense that we chose it,\n,
If you're miserable in your current situation,\n,
it's because you feel like some part of it is outside your control - that there's a problem you have no ability to solve, a problem that was somehow thrust upon you without your choosing.\n,
William James decided to conduct a little experiment. Spend one year believing that he was 100 percent responsible for everything that occurred in his life, no matter what. During this period, he would do everything in his power to change his circumstances, no matter the likelihood of failure. James would later refer to his little experiment as his "rebirth," and would credit it with everything that he later accomplished in his life.\n,
We are responsible for everything in our lives. We always control how we interpret what happens to us, as well as how we respond.\n
""","""
Fault is past tense. Responsibility is present tense. Fault results from choices that have already been made. Responsibility results from the choices you're currently making,\n,
Outrage is like a lot of other things that feel good but over time devour us from the inside out.\n,
Change is as simple as choosing to give a fuck about something else. It really is that simple. It's just not easy.\n,
Throughout my life, I've been flat-out wrong about myself, others, society, culture, the world, the universe - everything. And I hope that will continue to be the case for the rest of my life.\n,
When we learn we go from wrong to slightly less wrong, without actually ever reaching truth or perfection.\n,
Personal growth can actually be quite scientific.\n,
Our values are our hypotheses.\n,
Our actions are the experiments.\n,
The resulting emotions and thought patterns are our data.\n,
There is no correct ideology. There is only what your experience has shown you to be right for you.\n,
It's easier to sit in a painful certainty that nobody would find you attractive, that nobody appreciates your talents, than to actually test those beliefs and find out for sure.\n,
Be in constant search of doubt: about beliefs, feelings, or the future.\n,
Being wrong opens us up to the possibility of change.\n,
People five hundred years from now will laugh at us and our certainties today. They, too, will be wrong. Just less wrong than we were.\n,
Uncertainty is the root of all progress and all growth.\n
""","""
The more something threatens your identity, the more you will avoid it. That law applies to both good and bad. Making a million dollars, or becoming a famous rock star, could threaten your identity.\n,
"Finding yourself" can cement you into a strict role with unnecessary expectations, and close you off to potential and opportunities.\n,
Don't find yourself. Never know who you are.\n,
Let go of the idea that "you" exist at all.\n,
Don't be special. Don't be unique. Redefine your metrics in mundane and broad ways.\n,
Questions that will help you breed a little more uncertainty in your life:\n,
What if I'm wrong?\n,
What would it mean if I were wrong?\n,
Would being wrong create a better or a worse problem?\n,
It is the mark of an educated mind to be able to entertain a thought without accepting it.\n,
If it's down to me being screwed up, or everybody else being screwed up, it is far, far, far more likely that I'm the one who's screwed up.\n,
If it feels like it's you versus the world, chances are it's really just you versus yourself.\n,
A metric for the value "honesty," is never completely finished; it's a problem that must continuously be reengaged.\n,
"Buy a house and a nice car," once achieved, has nothing left to give you.\n,
The problem that drove you your entire adult life was just taken away from you.\n,
Goals like buy a lake house, lose fifteen pounds - are limited in the amount of happiness they can produce in our lives. They may be helpful when pursuing quick, short-term benefits, but as guides for the overall trajectory of our life, they suck.\n,
(On advice:) She feels so stuck that she ends up emailing a stranger on the Internet (me) and asking him an obvious question. From the outside, the answer is simple: just shut up and do it. But from the inside, from the perspective of each of these people, these questions feel impossibly complex. The problem here is pain. Asking a tutor out on a date is as simple as saying the words; risking intense embarrassment and rejection feels far more complicated.\n,
If you're stuck on a problem, don't sit there and think about it; just start working on it. Even if you don't know what you're doing, the simple act of working on it will eventually cause the right ideas to show up in your head.\n,
The only way to achieve meaning and a sense of importance in one's life is through a rejection of alternatives, a narrowing of freedom, a choice of commitment to one place, one belief, or one person.\n,
Russian frankness is unadulterated expression. Honesty in the truest sense of the word. Communication with no conditions, no strings attached, no ulterior motive, no sales job, no desperate attempt to be liked.\n,
Travel shows you that another society can live with entirely different values and still function.\n,
To build trust you have to be honest. That means when things suck, you say so openly.\n
""","""
There's a certain level of joy and meaning that you reach in life only when you've spent decades investing in a single relationship, a single craft, a single career. And you cannot achieve those decades of investment without rejecting the alternatives.\n,
We are defined by what we choose to reject.\n,
The desire to avoid rejection at all costs, to avoid confrontation and conflict, is a deep valueless, pleasure-driven, and self-absorbed life.\n,
Shakespeare wrote Romeo and Juliet not to celebrate romance, but rather to satirize it.\n,
The difference between a healthy and an unhealthy relationship comes down to two things:\n,
1) how well each person in the relationship accepts responsibility\n,
2) the willingness of each person to both reject and be rejected by their partner.\n,
It can be difficult for people to recognize the difference between doing something out of obligation and doing it voluntarily. So here's a litmus test:\n,
Ask yourself, "If I refused, how would the relationship change?"\n,
Similarly, ask, "If my partner refused something I wanted, how would the relationship change?"\n,
If the refusal would cause a blowout your relationship is conditional - based on superficial benefits received from one another, rather than on unconditional acceptance of each other.\n,
When trust is destroyed, it can be rebuilt only if the following two steps happen:\n,
1) the trust-breaker admits the true values that caused the breach and owns up to them\n,
2) the trust-breaker builds a solid track record of improved behavior over time.\n,
Commitment gives you freedom because you're no longer distracted by the unimportant and frivolous.\n,
Commitment gives you freedom because it hones your attention and focus, directing them toward what is most efficient at making you healthy and happy.\n,
Commitment makes decision-making easier and removes any fear of missing out; knowing that what you already have is good enough, why would you ever stress about chasing more, more, more again?\n,
Commitment allows you to focus intently on a few highly important goals and achieve a greater degree of success than you otherwise would.\n,
Breadth of experience is necessary and desirable to go out there and discover what seems worth investing yourself in. But depth is where the gold is buried.\n,
Ernest Becker book The Denial of Death: All of human civilization, he says, is basically a result of immortality projects that allow our conceptual self to live on way past the point of our physical death.\n,
People declare themselves experts, entrepreneurs, inventors, innovators, mavericks, and coaches without any real-life experience, because they feel
"""
    ]


def getpages():
    return pages
